"""empty message

Revision ID: 081461445c77
Revises: f269c63b881e
Create Date: 2018-08-17 08:48:29.493965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081461445c77'
down_revision = 'f269c63b881e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
